# Welcome to the config file!

# To change the blog settings according to your preference kindly change only in this file 
# and the rest of the changes will be updated in the blog

title: Salman Shah
email: sbs.191197@gmail.com
abstract: Salman Shah is a undergraduate student from NITK Surathkal receiving B. Tech in Information Technology. He works as a Backend Developer at Myntra Designs Pvt. Ltd. He is a contributor to Free and Open Source Software (FOSS).
keywords: Salman Shah, Backend Developer, Golang Evangelist, Traveller, Food Enthusiast, Open Source Enthusiast, Myntra, NITK Surathkal, salman-bhai
description: Family, Code, Speaker, Friends, Food and Travel in that order, that's him! Loves the hustle, deep desire to help people and impact their lives positively. Reach out for a conversation!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://salmanshah.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Information
author:
  name: Salman Shah

navigation:
  - title: Home
    link: /
  - title: Blog
    link: /blog/
  - title: About
    link: /about/

social-media:
  github: https://github.com/salman-bhai
  linkedin: https://www.linkedin.com/in/sbshah97
  facebook: https://www.facebook.com/sbshah97
  instagram: https://www.instagram.com/sbshah1997/
  twitter: https://twitter.com/sbshah97

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
theme: minima
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

gems:
  - jekyll-feed
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock

plugins: [jekyll-paginate]
paginate: 6
paginate_path: "/"

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 6

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################

future: true